---
title: "BST 210 Project"
author: "Yunyang Zhong"
date: '2022-11-03'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ipumsr)
library(nnet)
library(VGAM)
library(broom)
library(ResourceSelection)
library(pROC)
library(regclass)
ddi <- read_ipums_ddi("nhis_00002.xml")
data <- read_ipums_micro(ddi)

knitr::opts_chunk$set(warning = FALSE)
```

```{r}
data$AGE[data$AGE == 997] = NA
data$AGE[data$AGE == 999] = NA
data$AGE[data$AGE == 0] = NA

summary(data$AGE)
```

```{r}
data$sexcat <- NA
data$sexcat[data$SEX == 1] = "male"
data$sexcat[data$SEX == 2] = "female"
data$sexcat <- as.factor(data$sexcat)

summary(data$sexcat)
```

```{r}
data$sexoricat <- NA
data$sexoricat[data$SEXORIEN == 1] = "homosexual"
data$sexoricat[data$SEXORIEN == 2] = "heterosexual"
data$sexoricat[data$SEXORIEN == 3] = "bisexual"
data$sexoricat[data$SEXORIEN == 4] = "other"
data$sexoricat <- factor(data$sexoricat, levels = c("homosexual", "heterosexual", "bisexual", "other"))

summary(data$sexoricat)
```

```{r}
data$racecat <- NA
data$racecat[data$RACENEW == 100] = "white"
data$racecat[data$RACENEW == 200] = "black"
data$racecat[data$RACENEW == 300] = "aian"
data$racecat[data$RACENEW == 400] = "asian"
data$racecat[data$RACENEW > 400 & data$RACENEW < 900] = "other"
data$racecat <- as.factor(data$racecat)

summary(data$racecat)
```

```{r}
data$HOURSWRK[data$HOURSWRK > 95] = NA
data$HOURSWRK[data$HOURSWRK == 0] = NA

summary(data$HOURSWRK)
```

```{r}
data$incomecat <- NA
data$incomecat[data$INCFAM07ON == 11] = "under $34,999"
data$incomecat[data$INCFAM07ON == 12] = "$35,000-$49,999"
data$incomecat[data$INCFAM07ON == 22] = "$50,000-$74,999"
data$incomecat[data$INCFAM07ON == 23] = "$75,000-$99,999"
data$incomecat[data$INCFAM07ON == 24] = "over $100,000"
data$incomecat <- factor(data$incomecat, levels = c("under $34,999", "$35,000-$49,999", "$50,000-$74,999", "$75,000-$99,999", "over $100,000"))

summary(data$incomecat)
```

```{r}
data$healthcat <- NA
data$healthcat[data$HEALTH == 1] = "excellent"
data$healthcat[data$HEALTH == 2] = "very good"
data$healthcat[data$HEALTH == 3] = "good"
data$healthcat[data$HEALTH == 4] = "fair"
data$healthcat[data$HEALTH == 5] = "poor"
data$healthcat <- factor(data$healthcat, levels = c("excellent", "very good", "good", "fair", "poor"))

summary(data$healthcat)
```

```{r}
data$insurcat <- NA
data$insurcat[data$HINOTCOVE == 1] = "no"
data$insurcat[data$HINOTCOVE == 2] = "yes"
data$insurcat <- as.factor(data$insurcat)

summary(data$insurcat)
```

```{r}
data$MOD10DMIN[data$MOD10DMIN %in% c(0, 996, 997, 998, 999)] = NA

summary(data$MOD10DMIN)
```

```{r}
data$MOD10FWK[data$MOD10FWK == 0] = NA
data$MOD10FWK[data$MOD10FWK > 90] = NA

summary(data$MOD10FWK)
```

```{r}
data$anxiety <- NA
data$anxiety[data$ANXIETYEV == 1] = "No"
data$anxiety[data$ANXIETYEV == 2] = "Yes"
data$anxiety <- as.factor(data$anxiety)

summary(data$anxiety)
```

```{r}
data$depress <- NA
data$depress[data$DEPFREQ == 1] = "daily"
data$depress[data$DEPFREQ == 2] = "weekly"
data$depress[data$DEPFREQ == 3] = "monthly"
data$depress[data$DEPFREQ == 4] = "yearly"
data$depress[data$DEPFREQ == 5] = "never"
data$depress <- factor(data$depress, levels = c("never", "daily", "weekly", "monthly", "yearly"))

summary(data$depress)
```

```{r}
data$esupport <- NA
data$esupport[data$EMOSUPPORT == 1] = "always"
data$esupport[data$EMOSUPPORT == 2] = "usually"
data$esupport[data$EMOSUPPORT == 3] = "sometimes"
data$esupport[data$EMOSUPPORT == 4] = "rarely"
data$esupport[data$EMOSUPPORT == 5] = "never"
data$esupport <- factor(data$esupport, levels = c("always", "usually", "sometimes", "rarely", "never"))

summary(data$esupport)
```

```{r}
data$covid <- NA
data$covid[data$CVDTESTRSLT == 1] = "No"
data$covid[data$CVDTESTRSLT == 2] = "Yes"
data$covid <- as.factor(data$covid)

summary(data$covid)
```

```{r}
data$sympt <- NA
data$sympt[data$CVDSYMP == 1] = "no symptoms"
data$sympt[data$CVDSYMP == 2] = "mild symptoms"
data$sympt[data$CVDSYMP == 3] = "moderate symptoms"
data$sympt[data$CVDSYMP == 4] = "severe symptoms"
data$sympt <- factor(data$sympt, levels = c("no symptoms", "mild symptoms", "moderate symptoms", "severe symptoms"))

summary(data$sympt)
```

```{r}
data$reg <- NA
data$reg[data$REGION == 1] = "northeast"
data$reg[data$REGION == 2] = "midwest"
data$reg[data$REGION == 3] = "south"
data$reg[data$REGION == 4] = "west"
data$reg <- factor(data$reg, levels = c("northeast", "midwest", "south", "west"))

summary(data$reg)
```

```{r, results='hold'}
data <- data %>% 
  select(32:43, AGE, MOD10DMIN, MOD10FWK, -sexoricat, -insurcat, -covid)

data %>% 
  summary()

dim(data)[1]*0.05

dim(data %>% drop_na())[1]
```

> 3 numeric variables: age, duration of moderate activity 10+ minutues, frequency of moderate activity 10+ minutes


```{r}
data %>% 
  ggplot(aes(x = AGE)) +
  geom_density()

data %>% 
  ggplot(aes(x = MOD10DMIN)) +
  geom_density()

data %>% 
  ggplot(aes(x = MOD10FWK)) +
  geom_density()
```

```{r}
data %>% 
  filter(anxiety == "Yes") %>% 
  summary()
```

```{r}
data_multi <- data %>%
  select(-depress) %>%
  mutate(anxiety = case_when(is.na(anxiety) ~ "Unknown",
                             TRUE ~ as.character(anxiety)))

multi <- multinom(anxiety ~ ., data = data_multi)
AIC(multi)
BIC(multi)
tmulti = tidy(multi)
options(scipen = 999)
tmulti
tmulti$term[tmulti$p.value < 0.05]
```

```{r}
data_logis <- data %>% select(-depress) %>% filter(!is.na(anxiety))

logis <- glm(anxiety ~ ., family = binomial, data = data_logis)
AIC(logis)
BIC(logis)
tlogis = tidy(logis)
options(scipen = 999)
tlogis
tlogis$term[tlogis$p.value < 0.05]

# hoslem.test(logis$anxiety,fitted(logis),g=10)
 
predprob <- predict(logis,type=c("response"))
# roccurve <- roc(data_logis$anxiety ~ predprob)
# plot(roccurve,col="red")
# auc(roccurve)
 
logLik(logis)
VIF(logis)
```

```{r}
multi <- multinom(depress ~ ., data = data %>% select(-anxiety))
AIC(multi)
BIC(multi)
tmulti = tidy(multi)
options(scipen = 999)
tmulti
tmulti$term[tmulti$p.value < 0.05]
```

```{r}
ordin <- vglm(depress ~ ., cumulative(parallel=TRUE, reverse=TRUE), data = data %>% select(-anxiety))
AIC(ordin)
BIC(ordin)

data$depressdaily <- ifelse(data$depress=="daily", 1, 0)
data$depressnever <- ifelse(data$depress=="never", 1, 0)

moddaily <- glm(depressdaily ~ ., family=binomial, data=data %>% select(-anxiety, -depress, -depressnever)) 
summary(moddaily)

modnever <- glm(depressnever ~ ., family=binomial, data=data %>% select(-anxiety, -depress, -depressdaily)) 
summary(modnever)

coef(moddaily)[19:21]
coef(moddaily)[19] + c(-1, 1)*1.96*sqrt(vcov(moddaily)[19,19])
coef(moddaily)[20] + c(-1, 1)*1.96*sqrt(vcov(moddaily)[20,20])
coef(moddaily)[21] + c(-1, 1)*1.96*sqrt(vcov(moddaily)[21,21])
coef(modnever)[19:21]
coef(modnever)[19] + c(-1, 1)*1.96*sqrt(vcov(modnever)[19,19])
coef(modnever)[20] + c(-1, 1)*1.96*sqrt(vcov(modnever)[20,20])
coef(modnever)[21] + c(-1, 1)*1.96*sqrt(vcov(modnever)[21,21])
```
