---
title: "BST 210 Project"
date: '2022-12-05'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ipumsr)
library(nnet)
library(VGAM)
library(broom)
library(ResourceSelection)
library(pROC)
library(regclass)
library(splines2)
library(gam)
library(groupdata2)
library(caret)
ddi <- read_ipums_ddi("nhis_00002.xml")
data <- read_ipums_micro(ddi)

knitr::opts_chunk$set(warning = FALSE)
```

# Data Cleaning

```{r}
data <-
  data %>%
  select(AGE, SEX, RACENEW, INCFAM07ON, HEALTH, MOD10DMIN, ANXIETYEV, DEPFREQ, EMOSUPPORT, CVDSYMP, REGION) %>% 
  filter(MOD10DMIN != 000) %>% 
  filter(ANXIETYEV != 0) %>% 
  filter(DEPFREQ != 0) %>% 
  filter(EMOSUPPORT != 0) %>% 
  filter(CVDSYMP != 0)

data %>% summary()
```

```{r}
data$AGE[data$AGE == 997] = NA
data$AGE[data$AGE == 999] = NA

summary(data$AGE)
```

```{r}
data$sexcat <- NA
data$sexcat[data$SEX == 1] = "male"
data$sexcat[data$SEX == 2] = "female"
data$sexcat <- as.factor(data$sexcat)

summary(data$sexcat)
```

```{r}
data$racecat <- NA
data$racecat[data$RACENEW == 100] = "white"
data$racecat[data$RACENEW == 200] = "non-white"
data$racecat[data$RACENEW == 300] = "non-white"
data$racecat[data$RACENEW == 400] = "non-white"
data$racecat[data$RACENEW > 400 & data$RACENEW < 900] = "non-white"
data$racecat <- as.factor(data$racecat)

summary(data$racecat)
```

```{r}
data$incomecat <- NA
data$incomecat[data$INCFAM07ON == 11] = "under $49,999"
data$incomecat[data$INCFAM07ON == 12] = "under $49,999"
data$incomecat[data$INCFAM07ON == 22] = "$50,000-$99,999"
data$incomecat[data$INCFAM07ON == 23] = "$50,000-$99,999"
data$incomecat[data$INCFAM07ON == 24] = "over $100,000"
data$incomecat <- factor(data$incomecat, levels = c("under $49,999", "$50,000-$99,999", "over $100,000"))

summary(data$incomecat)
```

```{r}
data$healthcat <- NA
data$healthcat[data$HEALTH == 1] = "good"
data$healthcat[data$HEALTH == 2] = "good"
data$healthcat[data$HEALTH == 3] = "good"
data$healthcat[data$HEALTH == 4] = "fair"
data$healthcat[data$HEALTH == 5] = "poor"
data$healthcat <- factor(data$healthcat, levels = c("good", "fair", "poor"))

summary(data$healthcat)
```

```{r}
data$MOD10DMIN[data$MOD10DMIN %in% c(996, 997, 998, 999)] = NA

summary(data$MOD10DMIN)
```

```{r}
data$anxiety <- NA
data$anxiety[data$ANXIETYEV == 1] = "No"
data$anxiety[data$ANXIETYEV == 2] = "Yes"
data$anxiety <- factor(data$anxiety, levels = c("No", "Yes"))

summary(data$anxiety)
```

```{r}
data$depress <- NA
data$depress[data$DEPFREQ == 1] = "daily"
data$depress[data$DEPFREQ == 2] = "weekly or monthly"
data$depress[data$DEPFREQ == 3] = "weekly or monthly"
data$depress[data$DEPFREQ == 4] = "yearly"
data$depress[data$DEPFREQ == 5] = "never"
data$depress <- factor(data$depress, levels = c("never", "daily", "weekly or monthly", "yearly"))

summary(data$depress)
```

```{r}
data$esupport <- NA
data$esupport[data$EMOSUPPORT == 1] = "always"
data$esupport[data$EMOSUPPORT == 2] = "usually"
data$esupport[data$EMOSUPPORT == 3] = "sometimes-never"
data$esupport[data$EMOSUPPORT == 4] = "sometimes-never"
data$esupport[data$EMOSUPPORT == 5] = "sometimes-never"
data$esupport <- factor(data$esupport, levels = c("always", "usually", "sometimes-never"))

summary(data$esupport)
```

```{r}
data$sympt <- NA
data$sympt[data$CVDSYMP == 1] = "no symptoms"
data$sympt[data$CVDSYMP == 2] = "mild symptoms"
data$sympt[data$CVDSYMP == 3] = "moderate symptoms"
data$sympt[data$CVDSYMP == 4] = "severe symptoms"
data$sympt <- factor(data$sympt, levels = c("no symptoms", "mild symptoms", "moderate symptoms", "severe symptoms"))

summary(data$sympt)
```

```{r}
data$reg <- NA
data$reg[data$REGION == 1] = "northeast"
data$reg[data$REGION == 2] = "midwest"
data$reg[data$REGION == 3] = "south"
data$reg[data$REGION == 4] = "west"
data$reg <- factor(data$reg, levels = c("northeast", "midwest", "south", "west"))

summary(data$reg)
```

```{r}
data <- data %>% 
  select(12:20, AGE, MOD10DMIN)

data %>% 
  summary()

dim(data)[1]*0.05
```

# Modeling

## Anxiety - logistic

```{r}
data_logis <- data %>% select(-depress) %>% drop_na()
# data_logis <- upsample(data_logis, "anxiety")

logis1 <- glm(anxiety ~ AGE + sexcat + racecat + MOD10DMIN + healthcat + sympt + reg + esupport + incomecat, family = binomial, data = data_logis)
logis2 <- glm(anxiety ~ AGE + sexcat + racecat + MOD10DMIN + healthcat + sympt + esupport, family = binomial, data = data_logis)
logis3 <- glm(anxiety ~ AGE + sexcat + racecat + healthcat + sympt + esupport, family = binomial, data = data_logis)
logis4 <- glm(anxiety ~ AGE + sexcat + racecat + MOD10DMIN + healthcat + sympt, family = binomial, data = data_logis)
logis5 <- glm(anxiety ~ AGE + MOD10DMIN + healthcat + sympt + esupport, family = binomial, data = data_logis)
logis6 <- glm(anxiety ~ AGE + sexcat + racecat + healthcat + sympt, family = binomial, data = data_logis)
logis7 <- glm(anxiety ~ AGE + healthcat + sympt, family = binomial, data = data_logis)

data.frame(MODEL=c("logis1","logis2","logis3","logis4","logis5","logis6","logis7"),
           AIC=c(AIC(logis1),AIC(logis2),AIC(logis3),AIC(logis4),AIC(logis5),AIC(logis6),AIC(logis7)),
           BIC=c(BIC(logis1),BIC(logis2),BIC(logis3),BIC(logis4),BIC(logis5),BIC(logis6),BIC(logis7)))
```

```{r}
# options(scipen = 999)
tlogis1 = tidy(logis1)
tlogis2 = tidy(logis2)
tlogis3 = tidy(logis3)
tlogis4 = tidy(logis4)
tlogis5 = tidy(logis5)
tlogis6 = tidy(logis6)
tlogis7 = tidy(logis7)

tlogis1$term[tlogis1$p.value < 0.05]
tlogis2$term[tlogis2$p.value < 0.05]
tlogis3$term[tlogis3$p.value < 0.05]
tlogis4$term[tlogis4$p.value < 0.05]
tlogis5$term[tlogis5$p.value < 0.05]
tlogis6$term[tlogis6$p.value < 0.05]
tlogis7$term[tlogis7$p.value < 0.05]
```


```{r}
# hist(logis$fitted, main="p-hats")
# hist(hatvalues(logis), main="hat-values")

# options(digits=7)
# hoslem.test(logis1$anxiety,fitted(logis1),g=10)
# hoslem.test(model.frame(data_logis)$anxiety,fitted(logis2),g=10)
# hoslem.test(model.frame(data_logis)$anxiety,fitted(logis3),g=10)
# hoslem.test(model.frame(data_logis)$anxiety,fitted(logis4),g=10)
# hoslem.test(model.frame(data_logis)$anxiety,fitted(logis5),g=10)
# hoslem.test(model.frame(data_logis)$anxiety,fitted(logis6),g=10)
# hoslem.test(model.frame(data_logis)$anxiety,fitted(logis7),g=10)
 
predprob1 <- predict(logis1,type=c("response"))
roccurve1 <- roc(data_logis$anxiety ~ predprob1)
predprob2 <- predict(logis2,type=c("response"))
roccurve2 <- roc(data_logis$anxiety ~ predprob2)
predprob3 <- predict(logis3,type=c("response"))
roccurve3 <- roc(data_logis$anxiety ~ predprob3)
predprob4 <- predict(logis4,type=c("response"))
roccurve4 <- roc(data_logis$anxiety ~ predprob4)
predprob5 <- predict(logis5,type=c("response"))
roccurve5 <- roc(data_logis$anxiety ~ predprob5)
predprob6 <- predict(logis6,type=c("response"))
roccurve6 <- roc(data_logis$anxiety ~ predprob6)
predprob7 <- predict(logis7,type=c("response"))
roccurve7 <- roc(data_logis$anxiety ~ predprob7)
```


```{r}
data.frame(MODEL=c("logis1","logis2","logis3","logis4","logis5","logis6","logis7"),
           AIC=c(AIC(logis1),AIC(logis2),AIC(logis3),AIC(logis4),AIC(logis5),AIC(logis6),AIC(logis7)),
           BIC=c(BIC(logis1),BIC(logis2),BIC(logis3),BIC(logis4),BIC(logis5),BIC(logis6),BIC(logis7)),
           AUC=c(auc(roccurve1),auc(roccurve2),auc(roccurve3),auc(roccurve4),auc(roccurve5),auc(roccurve6),auc(roccurve7)))

# stepModel <- step(logis1, direction=c("both"))
pred<-ifelse(predict(logis3,type="response")>0.5,"Yes","No")
actu<-data_logis$anxiety
confusionMatrix(table(pred,actu))

pred<-ifelse(predict(logis6,type="response")>0.5,"Yes","No")
actu<-data_logis$anxiety
confusionMatrix(table(pred,actu))

VIF(logis3)
VIF(logis6)
```

## Depression - multinomial & ordinal

```{r}
data_multi <- data %>% select(-anxiety) %>% drop_na()
# data_multi <- upsample(data_multi, "depression")

multi1 <- glm(depress ~ AGE + sexcat + racecat + MOD10DMIN + healthcat + sympt + reg + esupport + incomecat, family = binomial, data = data_multi)
multi2 <- glm(depress ~ AGE + sexcat + racecat + MOD10DMIN + healthcat + sympt + esupport, family = binomial, data = data_multi)
multi3 <- glm(depress ~ AGE + sexcat + racecat + healthcat + sympt + esupport, family = binomial, data = data_multi)
multi4 <- glm(depress ~ AGE + sexcat + racecat + MOD10DMIN + healthcat + sympt, family = binomial, data = data_multi)
multi5 <- glm(depress ~ AGE + MOD10DMIN + healthcat + sympt + esupport, family = binomial, data = data_multi)
multi6 <- glm(depress ~ AGE + sexcat + racecat + healthcat + sympt, family = binomial, data = data_multi)
multi7 <- glm(depress ~ AGE + healthcat + sympt, family = binomial, data = data_multi)

data.frame(MODEL=c("multi1","multi2","multi3","multi4","multi5","multi6","multi7"),
           AIC=c(AIC(multi1),AIC(multi2),AIC(multi3),AIC(multi4),AIC(multi5),AIC(multi6),AIC(multi7)),
           BIC=c(BIC(multi1),BIC(multi2),BIC(multi3),BIC(multi4),BIC(multi5),BIC(multi6),BIC(multi7)))
```

```{r}
# options(scipen = 999)
tmulti1 = tidy(multi1)
tmulti2 = tidy(multi2)
tmulti3 = tidy(multi3)
tmulti4 = tidy(multi4)
tmulti5 = tidy(multi5)
tmulti6 = tidy(multi6)
tmulti7 = tidy(multi7)

tmulti1$term[tmulti1$p.value < 0.05]
tmulti2$term[tmulti2$p.value < 0.05]
tmulti3$term[tmulti3$p.value < 0.05]
tmulti4$term[tmulti4$p.value < 0.05]
tmulti5$term[tmulti5$p.value < 0.05]
tmulti6$term[tmulti6$p.value < 0.05]
tmulti7$term[tmulti7$p.value < 0.05]
```

```{r}
data_multi$depressdaily <- ifelse(data_multi$depress=="daily", 1, 0)
data_multi$depressnever <- ifelse(data_multi$depress=="never", 1, 0)
moddaily <- glm(depressdaily ~ ., family=binomial, data=data_multi %>% select(-depress, -depressnever)) 
summary(moddaily)
modnever <- glm(depressnever ~ ., family=binomial, data=data_multi %>% select(-depress, -depressdaily)) 
summary(modnever)
coef(moddaily)[10:12]
coef(moddaily)[10] + c(-1, 1)*1.96*sqrt(vcov(moddaily)[10,10])
coef(moddaily)[11] + c(-1, 1)*1.96*sqrt(vcov(moddaily)[11,11])
coef(moddaily)[12] + c(-1, 1)*1.96*sqrt(vcov(moddaily)[12,12])
coef(modnever)[10:12]
coef(modnever)[10] + c(-1, 1)*1.96*sqrt(vcov(modnever)[10,10])
coef(modnever)[11] + c(-1, 1)*1.96*sqrt(vcov(modnever)[11,11])
coef(modnever)[12] + c(-1, 1)*1.96*sqrt(vcov(modnever)[12,12])
```